baseURL = 'https://blog.bythe.rocks/'
languageCode = 'en-us'
title = 'My Blog'

# Enable robots.txt
enableRobotsTXT = true

# Disable taxonomy (tags/categories)
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

# Code highlighting configuration
[markup]
  [markup.highlight]
    style = 'friendly'
    lineNos = false
    codeFences = true

[params]
  description = "Clojure, programming, and occasional thoughts about bytes and nibbles"
  
  # Use ISO date format
  dateFormat = "2006-01-02"
  
  # Hide the "Made with" line
  hideMadeWithLine = true

# Main menu
[menu]
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 10
